// <auto-generated />
using System;
using Ecomerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecomerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Ecomerce.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PreviewDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ShoppingDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserCustomerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserSellerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserCustomerId");

                    b.HasIndex("UserSellerId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.UserCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCustomers");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.UserCustomerProperties.ShoppingCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantify")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UserCustomerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserCustomerId")
                        .IsUnique();

                    b.ToTable("ShoppingCars");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.UserSeller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSellers");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacteristicsSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Characteristics");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ShoppingCarId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserSellerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("ShoppingCarId");

                    b.HasIndex("UserSellerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.Delivery", b =>
                {
                    b.HasOne("Ecomerce.Models.UserProperties.Operation", "Operation")
                        .WithOne("Delivery")
                        .HasForeignKey("Ecomerce.Models.UserProperties.Delivery", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.Operation", b =>
                {
                    b.HasOne("Ecomerce.Models.UserProperties.UserCustomer", "UserCustomer")
                        .WithMany("Shopping")
                        .HasForeignKey("UserCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecomerce.Models.UserProperties.UserSeller", "UserSeller")
                        .WithMany("Operations")
                        .HasForeignKey("UserSellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCustomer");

                    b.Navigation("UserSeller");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.UserCustomer", b =>
                {
                    b.HasOne("Ecomerce.Models.User", "User")
                        .WithOne("UserCustomer")
                        .HasForeignKey("Ecomerce.Models.UserProperties.UserCustomer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.UserCustomerProperties.ShoppingCar", b =>
                {
                    b.HasOne("Ecomerce.Models.UserProperties.UserCustomer", "UserCustomer")
                        .WithOne("ShoppingCar")
                        .HasForeignKey("Ecomerce.Models.UserProperties.UserCustomerProperties.ShoppingCar", "UserCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCustomer");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.UserSeller", b =>
                {
                    b.HasOne("Ecomerce.Models.User", "User")
                        .WithOne("UserSeller")
                        .HasForeignKey("Ecomerce.Models.UserProperties.UserSeller", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Ecomerce.Models.UserProperties.Operation", "Operation")
                        .WithOne("Product")
                        .HasForeignKey("Product", "OperationId");

                    b.HasOne("Ecomerce.Models.UserProperties.UserCustomerProperties.ShoppingCar", "ShoppingCar")
                        .WithMany("Products")
                        .HasForeignKey("ShoppingCarId");

                    b.HasOne("Ecomerce.Models.UserProperties.UserSeller", "UserSeller")
                        .WithMany("Products")
                        .HasForeignKey("UserSellerId");

                    b.Navigation("Operation");

                    b.Navigation("ShoppingCar");

                    b.Navigation("UserSeller");
                });

            modelBuilder.Entity("Ecomerce.Models.User", b =>
                {
                    b.Navigation("UserCustomer");

                    b.Navigation("UserSeller");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.Operation", b =>
                {
                    b.Navigation("Delivery")
                        .IsRequired();

                    b.Navigation("Product")
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.UserCustomer", b =>
                {
                    b.Navigation("Shopping");

                    b.Navigation("ShoppingCar")
                        .IsRequired();
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.UserCustomerProperties.ShoppingCar", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ecomerce.Models.UserProperties.UserSeller", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
